### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by Tecnico1931** [brysontyrrell/StaticGroupFromSearch#1]
Traceback (most recent call last):
  File "/Users/*****_/Desktop/StaticGroupFromSearch-master/StaticGroupFromSearch.py", line 136, in <module>
    results = jss.get_match(i)
  File "/Users/**_**/Desktop/StaticGroupFromSearch-master/StaticGroupFromSearch.py", line 78, in get_match
    print("an error occurred during the GET: {0}".format(e.code))
AttributeError: 'URLError' object has no attribute 'code'

**Comment by brysontyrrell** [comment]
This is an example of me being lazy and not handling specific exceptions. I'll update this to handle different exceptions and provide better feedback.  Generally URLError involves the address passed to the script.  I can probably handle the input better, but double-check that for starts.

**Comment by brysontyrrell** [comment]
The version I just committed should address the uncaught Exceptions that were being thrown.
